# The name given to the MariaDB/MySQL service (lowercase alphanumeric only).
db:
    type: mariadb:10.5
    # The type of your service (mariadb), which uses the format
    # 'type:version'. Be sure to consult the MariaDB/MySQL documentation
    # (https://docs.platform.sh/add-services/mysql.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 2048

phpmyadmin:
    type: phpmyadmin
    relationships:
        database: "db:mariadb"

